#ifndef __DEBUG__
#define __DEBUG__
#include <X11/Xlib.h>
#include <X11/Xproto.h>
#include <stdio.h>

#define __log__(sink, ...)                                                     \
  {                                                                            \
    fprintf(sink, __VA_ARGS__);                                                \
    fflush(sink);                                                              \
  }
#define LOG(...)   __log__(stdout, __VA_ARGS__)
#define ERROR(...) __log__(stderr, __VA_ARGS__)

#define REPR(x) [x] = #x
static const char *const EventRepr[LASTEvent] = {
    REPR(KeyPress),         REPR(KeyRelease),       REPR(ButtonPress),
    REPR(ButtonRelease),    REPR(MotionNotify),     REPR(EnterNotify),
    REPR(LeaveNotify),      REPR(FocusIn),          REPR(FocusOut),
    REPR(KeymapNotify),     REPR(Expose),           REPR(GraphicsExpose),
    REPR(NoExpose),         REPR(VisibilityNotify), REPR(CreateNotify),
    REPR(DestroyNotify),    REPR(UnmapNotify),      REPR(MapNotify),
    REPR(MapRequest),       REPR(ReparentNotify),   REPR(ConfigureNotify),
    REPR(ConfigureRequest), REPR(GravityNotify),    REPR(ResizeRequest),
    REPR(CirculateNotify),  REPR(CirculateRequest), REPR(PropertyNotify),
    REPR(SelectionClear),   REPR(SelectionRequest), REPR(SelectionNotify),
    REPR(ColormapNotify),   REPR(ClientMessage),    REPR(MappingNotify),
    REPR(GenericEvent),
};

static const char *const RequestCodes[] = {
    REPR(X_CreateWindow),
    REPR(X_ChangeWindowAttributes),
    REPR(X_GetWindowAttributes),
    REPR(X_DestroyWindow),
    REPR(X_DestroySubwindows),
    REPR(X_ChangeSaveSet),
    REPR(X_ReparentWindow),
    REPR(X_MapWindow),
    REPR(X_MapSubwindows),
    REPR(X_UnmapWindow),
    REPR(X_UnmapSubwindows),
    REPR(X_ConfigureWindow),
    REPR(X_CirculateWindow),
    REPR(X_GetGeometry),
    REPR(X_QueryTree),
    REPR(X_InternAtom),
    REPR(X_GetAtomName),
    REPR(X_ChangeProperty),
    REPR(X_DeleteProperty),
    REPR(X_GetProperty),
    REPR(X_ListProperties),
    REPR(X_SetSelectionOwner),
    REPR(X_GetSelectionOwner),
    REPR(X_ConvertSelection),
    REPR(X_SendEvent),
    REPR(X_GrabPointer),
    REPR(X_UngrabPointer),
    REPR(X_GrabButton),
    REPR(X_UngrabButton),
    REPR(X_ChangeActivePointerGrab),
    REPR(X_GrabKeyboard),
    REPR(X_UngrabKeyboard),
    REPR(X_GrabKey),
    REPR(X_UngrabKey),
    REPR(X_AllowEvents),
    REPR(X_GrabServer),
    REPR(X_UngrabServer),
    REPR(X_QueryPointer),
    REPR(X_GetMotionEvents),
    REPR(X_TranslateCoords),
    REPR(X_WarpPointer),
    REPR(X_SetInputFocus),
    REPR(X_GetInputFocus),
    REPR(X_QueryKeymap),
    REPR(X_OpenFont),
    REPR(X_CloseFont),
    REPR(X_QueryFont),
    REPR(X_QueryTextExtents),
    REPR(X_ListFonts),
    REPR(X_ListFontsWithInfo),
    REPR(X_SetFontPath),
    REPR(X_GetFontPath),
    REPR(X_CreatePixmap),
    REPR(X_FreePixmap),
    REPR(X_CreateGC),
    REPR(X_ChangeGC),
    REPR(X_CopyGC),
    REPR(X_SetDashes),
    REPR(X_SetClipRectangles),
    REPR(X_FreeGC),
    REPR(X_ClearArea),
    REPR(X_CopyArea),
    REPR(X_CopyPlane),
    REPR(X_PolyPoint),
    REPR(X_PolyLine),
    REPR(X_PolySegment),
    REPR(X_PolyRectangle),
    REPR(X_PolyArc),
    REPR(X_FillPoly),
    REPR(X_PolyFillRectangle),
    REPR(X_PolyFillArc),
    REPR(X_PutImage),
    REPR(X_GetImage),
    REPR(X_PolyText8),
    REPR(X_PolyText16),
    REPR(X_ImageText8),
    REPR(X_ImageText16),
    REPR(X_CreateColormap),
    REPR(X_FreeColormap),
    REPR(X_CopyColormapAndFree),
    REPR(X_InstallColormap),
    REPR(X_UninstallColormap),
    REPR(X_ListInstalledColormaps),
    REPR(X_AllocColor),
    REPR(X_AllocNamedColor),
    REPR(X_AllocColorCells),
    REPR(X_AllocColorPlanes),
    REPR(X_FreeColors),
    REPR(X_StoreColors),
    REPR(X_StoreNamedColor),
    REPR(X_QueryColors),
    REPR(X_LookupColor),
    REPR(X_CreateCursor),
    REPR(X_CreateGlyphCursor),
    REPR(X_FreeCursor),
    REPR(X_RecolorCursor),
    REPR(X_QueryBestSize),
    REPR(X_QueryExtension),
    REPR(X_ListExtensions),
    REPR(X_ChangeKeyboardMapping),
    REPR(X_GetKeyboardMapping),
    REPR(X_ChangeKeyboardControl),
    REPR(X_GetKeyboardControl),
    REPR(X_Bell),
    REPR(X_ChangePointerControl),
    REPR(X_GetPointerControl),
    REPR(X_SetScreenSaver),
    REPR(X_GetScreenSaver),
    REPR(X_ChangeHosts),
    REPR(X_ListHosts),
    REPR(X_SetAccessControl),
    REPR(X_SetCloseDownMode),
    REPR(X_KillClient),
    REPR(X_RotateProperties),
    REPR(X_ForceScreenSaver),
    REPR(X_SetPointerMapping),
    REPR(X_GetPointerMapping),
    REPR(X_SetModifierMapping),
    REPR(X_GetModifierMapping),
    REPR(X_NoOperation),
};
#undef REPR
#endif
